<template>
  <div>
    <Heading size="xl" class="mb-6">My Billing</Heading>

    <div v-if="loading" class="flex justify-center py-12">
      <LoadingSpinner />
    </div>

    <div v-else-if="error" class="mb-6">
      <ErrorAlert :message="error" />
    </div>

    <div v-else class="bg-white rounded-lg shadow overflow-hidden">
      <div v-if="bills.length === 0" class="p-8 text-center text-gray-500">
        <p class="text-lg mb-2">No bills found.</p>
        <p class="text-sm">Bills will appear here once they are generated by the admin.</p>
      </div>

      <div v-else class="divide-y divide-gray-200">
        <div
          v-for="bill in bills"
          :key="bill.id"
          class="p-6 hover:bg-gray-50 transition-colors"
        >
          <div class="flex items-center justify-between">
            <div class="flex-1">
              <p class="text-lg font-medium text-gray-900">
                {{ getChildName(bill.child_id) }} - {{ getMonthName(bill.month) }} {{ bill.year }}
              </p>
              <div class="mt-2 grid grid-cols-3 gap-4 text-sm">
                <div>
                  <span class="text-gray-600">Total:</span>
                  <span class="ml-2 font-medium">€{{ bill.total_amount.toFixed(2) }}</span>
                </div>
                <div>
                  <span class="text-gray-600">Paid:</span>
                  <span class="ml-2 font-medium">€{{ bill.paid_amount.toFixed(2) }}</span>
                </div>
                <div>
                  <span class="text-gray-600">Refund:</span>
                  <span class="ml-2 font-medium text-green-600">€{{ bill.refund_amount.toFixed(2) }}</span>
                </div>
              </div>
              <div class="mt-2 flex items-center gap-4">
                <span
                  :class="[
                    'px-2 py-1 text-xs font-medium rounded-full',
                    bill.status === 'paid' ? 'bg-green-100 text-green-800' :
                    bill.status === 'overdue' ? 'bg-red-100 text-red-800' :
                    'bg-yellow-100 text-yellow-800'
                  ]"
                >
                  {{ bill.status }}
                </span>
                <span class="text-xs text-gray-500">
                  Due: {{ formatDate(bill.due_date) }}
                </span>
              </div>
            </div>
            <div class="flex gap-2">
              <NuxtLink
                :to="`/parent/billing/${bill.id}`"
                class="text-blue-600 hover:text-blue-700 text-sm"
              >
                View Details →
              </NuxtLink>
              <button
                v-if="bill.document_url"
                @click="downloadDocument(bill.id)"
                class="text-green-600 hover:text-green-700 text-sm"
              >
                Download PDF
              </button>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import { onMounted } from 'vue'
import { storeToRefs } from 'pinia'
import { useBillingStore } from '~/stores/billing'
import { useChildrenStore } from '~/stores/children'
import { useAuthStore } from '~/stores/auth'
import Heading from '~/components/ui/Heading.vue'
import LoadingSpinner from '~/components/common/LoadingSpinner.vue'
import ErrorAlert from '~/components/common/ErrorAlert.vue'

definePageMeta({
  middleware: ['auth', 'role'],
  role: 'parent'
})

const billingStore = useBillingStore()
const childrenStore = useChildrenStore()
const authStore = useAuthStore()

const { bills, loading, error } = storeToRefs(billingStore)
const { children } = storeToRefs(childrenStore)

onMounted(async () => {
  await childrenStore.fetchChildren()
  // Fetch bills for all parent's children
  // RLS will filter automatically
  await billingStore.fetchBillsForParent()
})

const getChildName = (childId: string) => {
  const child = children.value.find(c => c.id === childId)
  return child ? `${child.first_name} ${child.last_name}` : childId
}

const getMonthName = (month: number) => {
  const date = new Date(2000, month - 1, 1)
  return date.toLocaleString('default', { month: 'long' })
}

const formatDate = (date: string) => {
  return new Date(date).toLocaleDateString()
}

const downloadDocument = async (billingId: string) => {
  try {
    const response = await $fetch('/api/admin/lunch/billing/get-document', {
      method: 'GET',
      params: { billing_id: billingId }
    })

    if (response.success && response.signed_url) {
      window.open(response.signed_url, '_blank')
    }
  } catch (e: any) {
    alert(e.data?.message || e.message || 'Failed to get document')
  }
}
</script>
